<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="weatherreading">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="temperature" type="xs:float"/>

      <xs:element name="pressure">
        <xs:simpleType>
        <xs:restriction base="xs:float">
            <xs:minInclusive value="295"/>
            <xs:maxInclusive value="405"/>
        </xs:restriction> 
      </xs:simpleType>
      </xs:element>
      
      <xs:element name="humidity">
        <xs:simpleType>
            <xs:restriction base="xs:float">
                <xs:minInclusive value="20"/>
                <xs:maxInclusive value="100"/>
            </xs:restriction> 
      </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="readings">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="weatherreading" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>